spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: root
    password: root
  liquibase:
    default-schema: restaurant_collection
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: restaurant_collection
