spring:
  datasource:
    url: jdbc:postgresql://postgres_db/postgres_aston
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: restaurant_collection
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: restaurant_collection
server:
  port: 8080
